"""Restricted Python executor for running Pandas code generated by the Analysis LLM."""

from __future__ import annotations

import math
import time
from typing import Any

import numpy as np
import pandas as pd


# Maximum wall-clock seconds a single generated code block may run.
_CODE_TIMEOUT = 15.0

# Safe subset of builtins available to generated code.
_SAFE_BUILTINS: dict[str, Any] = {
    "True": True,
    "False": False,
    "None": None,
    "len": len,
    "list": list,
    "dict": dict,
    "tuple": tuple,
    "str": str,
    "int": int,
    "float": float,
    "bool": bool,
    "range": range,
    "zip": zip,
    "enumerate": enumerate,
    "round": round,
    "abs": abs,
    "max": max,
    "min": min,
    "sum": sum,
    "sorted": sorted,
    "reversed": reversed,
    "isinstance": isinstance,
    "type": type,
    "filter": filter,
    "map": map,
    "any": any,
    "all": all,
    "print": print,  # harmless; output not captured
    "Exception": Exception,
    "ValueError": ValueError,
    "TypeError": TypeError,
    "KeyError": KeyError,
    "ZeroDivisionError": ZeroDivisionError,
}


class CodeExecutionError(RuntimeError):
    """Raised when generated Pandas code fails or breaks safety rules."""


def analyse(code: str, dataframes: dict[str, pd.DataFrame]) -> Any:
    """Execute *code* in a restricted namespace and return the value of ``result``.

    Parameters
    ----------
    code:
        Python code that must assign its answer to a ``result`` variable.
    dataframes:
        DataFrames made available to the code under their dict keys as variable names.

    Returns
    -------
    The JSON-serialisable value bound to ``result``.

    Raises
    ------
    CodeExecutionError
        If the code fails to compile, raises an exception, runs too long, or does
        not set ``result``.
    """
    namespace: dict[str, Any] = {
        "__builtins__": _SAFE_BUILTINS,
        "pd": pd,
        "np": np,
        **dataframes,
    }

    try:
        compiled = compile(code, "<analysis_code>", "exec")
    except SyntaxError as exc:
        raise CodeExecutionError(f"Generated code has a syntax error: {exc}") from exc

    deadline = time.perf_counter() + _CODE_TIMEOUT

    def time_check(frame, event, arg) -> None:  # noqa: ANN001
        if event in ("call", "line") and time.perf_counter() > deadline:
            raise TimeoutError("Code execution timed out.")

    try:
        import sys
        old_trace = sys.settrace(time_check)
        exec(compiled, namespace)
        sys.settrace(old_trace)
    except TimeoutError:
        raise CodeExecutionError("The analysis code took too long and was stopped.")  # noqa: B904
    except Exception as exc:
        raise CodeExecutionError(f"Analysis code failed: {type(exc).__name__}: {exc}")  # noqa: B904

    if "result" not in namespace:
        raise CodeExecutionError("Generated code did not set a `result` variable.")

    value = namespace["result"]
    return _json_safe(value)


def _json_safe(value: Any) -> Any:
    """Convert Pandas and NumPy values into JSON-safe Python types."""
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    if isinstance(value, pd.Timedelta):
        return str(value)
    if isinstance(value, pd.DataFrame):
        return value.to_dict(orient="records")
    if isinstance(value, pd.Series):
        return value.tolist()
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        v = float(value)
        if math.isnan(v) or math.isinf(v):
            return None
        return v
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, dict):
        return {str(k): _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return None
        return value
    return value